package com.careeranalyzer.util;

import com.careeranalyzer.analyzer.CareerMatcher;
import com.careeranalyzer.model.Career;
import com.careeranalyzer.model.Skill;
import com.careeranalyzer.model.Student;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

public class FileManager {

    private static final String REPORT_FOLDER =
            "output/reports";

    public void saveReport(
            Student student,
            List<CareerMatcher.CareerResult> results,
            Career recommendedCareer) {

        File folder = new File(REPORT_FOLDER);

        if (!folder.exists()) {
            folder.mkdirs();
        }

        String safeName =
                student.getName()
                        .replaceAll("[^a-zA-Z0-9]", "_");

        String fileName =
                REPORT_FOLDER +
                        "/" +
                        safeName +
                        "_career_report.txt";

        try (PrintWriter writer =
                     new PrintWriter(
                             new FileWriter(fileName))) {

            writer.println(
                    "=========================================="
            );

            writer.println(
                    "      STUDENT CAREER ANALYSIS REPORT"
            );

            writer.println(
                    "=========================================="
            );

            writer.println();

            writer.println(
                    "Student Name : " +
                            student.getName()
            );

            writer.println(
                    "Branch       : " +
                            student.getBranch()
            );

            writer.println(
                    "CGPA         : " +
                            student.getCgpa()
            );

            writer.println();

            writer.println("SKILLS");
            writer.println("----------------------------");

            for (Skill skill : student.getSkills()) {

                writer.printf(
                        "%-25s %.2f%n",
                        skill.getName(),
                        skill.getScore()
                );
            }

            writer.println();

            writer.println("CAREER MATCHES");
            writer.println("----------------------------");

            int rank = 1;

            for (CareerMatcher.CareerResult result :
                    results) {

                writer.printf(
                        "%d. %-30s %.2f%%%n",
                        rank++,
                        result.getCareer().getName(),
                        result.getMatchScore()
                );
            }

            writer.println();

            writer.println(
                    "RECOMMENDED CAREER"
            );

            writer.println("----------------------------");

            writer.println(
                    recommendedCareer.getName()
            );

            writer.println();

            writer.println(
                    "Report generated by " +
                            "Student Skill & Career Path Analyzer."
            );

            System.out.println(
                    "\nReport saved successfully:"
            );

            System.out.println(fileName);

        } catch (IOException e) {

            System.out.println(
                    "Error while saving report: " +
                            e.getMessage()
            );
        }
    }
}